# Generated by Django 3.0.2 on 2020-02-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerTask',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_state', models.BooleanField(default=True)),
                ('user_name', models.CharField(max_length=30)),
                ('platform', models.CharField(max_length=30)),
                ('account', models.CharField(max_length=30)),
                ('weChatID', models.CharField(max_length=30)),
                ('crawl_start', models.DateTimeField()),
                ('crawl_end', models.DateTimeField()),
                ('task_start', models.DateTimeField()),
                ('task_end', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='task_state',
            field=models.BooleanField(default=False),
        ),
    ]
